[package]
name = "libaaarg"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
rand = "0.8.5"
rodio = "0.15"
